In [1]:
import pandas as pd
import numpy as np

In [32]:
party_data = pd.read_csv("../delegates/COP28_delegates_all.csv")
party_data = party_data.query("type=='Parties'")
party_names_list = party_data["nominator"].unique()
party_names_list

array(['Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda',
       'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan',
       'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
       'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia (Plurinational State of)', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo', 'Cook Islands', 'Costa Rica',
       "Côte d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czechia',
       "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'European Union', 'Fiji', 'Finland',
       'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana',
       'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau',
       'Guyana', 'Haiti', 'Holy See', 'Honduras', 'Hungary', 'Iceland',
       'India', 'Indonesia', 'Iran (Islamic Republic of)', 'Iraq',
       'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan',
       "Lao People's Democratic Republic", 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia (Federated States of)', 'Monaco', 'Mongolia',
       'Montenegro', 'Morocco', 'Mozambique', 'Namibia', 'Nauru', 'Nepal',
       'Netherlands (Kingdom of the)', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'Niue', 'North Macedonia', 'Norway', 'Oman',
       'Pakistan', 'Palau', 'Panama', 'Papua New Guinea', 'Paraguay',
       'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar',
       'Republic of Korea', 'Republic of Moldova', 'Romania',
       'Russian Federation', 'Rwanda', 'Saint Kitts and Nevis',
       'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'State of Palestine', 'Sudan', 'Suriname',
       'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Tajikistan',
       'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago',
       'Tunisia', 'Türkiye', 'Turkmenistan', 'Tuvalu', 'Uganda',
       'Ukraine', 'United Arab Emirates',
       'United Kingdom of Great Britain and Northern Ireland',
       'United Republic of Tanzania', 'United States of America',
       'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela (Bolivarian Republic of)', 'Viet Nam', 'Yemen',
       'Zambia', 'Zimbabwe'], dtype=object)

In [22]:
annex_one = ["Australia","Austria","Belarus","Belgium","Bulgaria","Canada","Denmark","Estonia","Finland",
                  "France","Germany","Greece","Hungary","Iceland","Ireland","Italy","Japan","Latvia","Lithuania",
                  "Luxembourg","Netherlands (Kingdom of the)","New Zealand","Norway","Poland","Portugal","Romania",
                  "Russian Federation","Spain","Sweden","Switzerland","Türkiye","Ukraine",
                  "United Kingdom of Great Britain and Northern Ireland","United States of America","Croatia",
                  "Czechia","Liechtenstein","Monaco","Slovakia","Slovenia", "Malta","Cyprus"]
annex_two = ["Australia","Austria","Belgium","Canada","Denmark","Finland","France","Germany",
             "Greece","Iceland","Ireland","Italy","Japan","Luxembourg","Netherlands (Kingdom of the)",
             "New Zealand","Norway","Portugal","Spain","Sweden","Switzerland",
             "United Kingdom of Great Britain and Northern Ireland","United States of America"]

In [31]:
party_names = pd.DataFrame(data={"party":party_names_list})
for i in party_names.index:
    if party_names.loc[i,"party"] in annex_one:
        party_names.loc[i,"annex_1"] = 1
        if party_names.loc[i,"party"] in annex_two:
            party_names.loc[i,"annex_2"] = 1
            party_names.loc[i,"type"] = "Annex II"
        else:
            party_names.loc[i,"type"] = "Annex I Only"
    else:
        party_names.loc[i,"type"] = "Non-Annex"
party_names = party_names.fillna(0)
party_names.set_index("party").to_csv("org_list_party.csv")
party_names.set_index("party").to_excel("org_list_party.xlsx")

party_names

                                  party       type  annex_1  annex_2
0                               Albania  Non-Annex      0.0      0.0
1                               Algeria  Non-Annex      0.0      0.0
2                               Andorra  Non-Annex      0.0      0.0
3                                Angola  Non-Annex      0.0      0.0
4                   Antigua and Barbuda  Non-Annex      0.0      0.0
..                                  ...        ...      ...      ...
190  Venezuela (Bolivarian Republic of)  Non-Annex      0.0      0.0
191                            Viet Nam  Non-Annex      0.0      0.0
192                               Yemen  Non-Annex      0.0      0.0
193                              Zambia  Non-Annex      0.0      0.0
194                            Zimbabwe  Non-Annex      0.0      0.0

[195 rows x 4 columns]